name: cipher
version: 0.7.2
author: Iván Zaera Avellón <izaera@gmail.com>
description: A Dart library implementing cryptographic algorithms.
homepage: http://izaera.github.io/cipher/
environment:
  sdk: '>=1.11.0'
documentation: http://izaera.github.io/cipher/api/
dependencies:
  bignum: '^0.1.0'
  fixnum: '^0.10.4'
dev_dependencies:
  benchmark_harness: '^1.0.4'
  browser: '^0.10.0'
  test: "^0.12.13+1"
